### ISSUE TITLE
antspyx 0.3.2 is expired

### ISSUE THREAD

**Issue by npardakhti** [MIDIconsortium/BrainAge#4]
antspyx==0.3.2 is expired and preprocessed nii.gz files aren't saved anymore while running fine_tune.py.

**Comment by allertec** [comment]
+1

**Comment by davvwood** [comment]
fixed by updating antspy install (now requires python >= 3.8 and takes longer to run 'pip install -r requirements.txt'

**Comment by davvwood** [comment]
closing as fixed
